# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

services:
  mysql-standalone-container:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    volumes:
      - /data/mysql
  springboot-docker-compose-mysql-app-container:
    image: spring-app
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone-container
    ports:
      - "8080:8080"
    volumes:
      - /data/springboot-docker-compose-mysql-app
    expose:
      - "8080"